env:
  browser: true
  commonjs: true
  es6: true
  mocha: true
  jest: true
extends:
  - airbnb
  - prettier
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
parser: babel-eslint
plugins:
  - react
  - jsx-a11y
  - jest
  - prettier
rules:
  react/jsx-filename-extension: 0
  react/prop-types: 0
  no-underscore-dangle: 0
  prettier/prettier: error
